#!/bin/sh

# Colors
GREEN='\033[1;32m'
YELLOW='\033[0;33m'
RED='\033[1;31m'
NC='\033[0m' # No Color

function printGreen() {
     printf "${GREEN}$1${NC}"
}

function printGreenLn() {
     printf "${GREEN}$1${NC}\n"
}

